// examples/frameworks/vue/src/App.vue
<script setup lang="ts">
import { computed, ref, useTemplateRef } from 'vue';
import type { LyraInput } from '@aceshooting/lyra-ui/components/lr-input.js';
import type { TableColumn } from '@aceshooting/lyra-ui/components/lr-table.js';
import type {} from '@aceshooting/lyra-ui/vue';

interface Person {
  id: number;
  name: string;
  role: string;
}

const input = useTemplateRef<LyraInput>('input');
const query = ref('');
const people: Person[] = [
  { id: 1, name: 'Ada Lovelace', role: 'Analyst' },
  { id: 2, name: 'Grace Hopper', role: 'Engineer' },
  { id: 3, name: 'Katherine Johnson', role: 'Mathematician' },
];
function personFrom(row: unknown): Person {
  return row as Person;
}
const columns: TableColumn<unknown>[] = [
  { key: 'name', label: 'Name', cell: (row) => personFrom(row).name, sortable: true },
  { key: 'role', label: 'Role', cell: (row) => personFrom(row).role },
];
const rowKey = (row: unknown) => personFrom(row).id;
const rows = computed(() =>
  people.filter((person) => person.name.toLowerCase().includes(query.value.toLowerCase())),
);

function onChange(event: CustomEvent<{ value: string }>): void {
  query.value = event.detail.value;
}
</script>

<template>
  <main class="lr-native lr-stack lr-gap-l">
    <header class="lr-stack lr-gap-xs">
      <h1>People</h1>
      <p>Vue's property modifier keeps array values out of string attributes.</p>
    </header>

    <div class="lr-cluster lr-gap-s">
      <lr-input
        ref="input"
        label="Filter by name"
        :value="query"
        with-clear
        @lr-change="onChange"
      />
      <button type="button" @click="input?.select()">Select filter text</button>
    </div>

    <lr-table
      aria-label="People matching the filter"
      :row-key.prop="rowKey"
      :columns.prop="columns"
      :rows.prop="rows"
    />
  </main>
</template>

// examples/frameworks/svelte/src/App.svelte
<script lang="ts">
  import type { LyraInput } from '@aceshooting/lyra-ui/components/lr-input.js';
  import type { TableColumn } from '@aceshooting/lyra-ui/components/lr-table.js';
  import type {} from '@aceshooting/lyra-ui/svelte';

  interface Person {
    id: number;
    name: string;
    role: string;
  }

  let input: LyraInput;
  let query = '';
  const people: Person[] = [
    { id: 1, name: 'Ada Lovelace', role: 'Analyst' },
    { id: 2, name: 'Grace Hopper', role: 'Engineer' },
    { id: 3, name: 'Katherine Johnson', role: 'Mathematician' },
  ];
  function personFrom(row: unknown): Person {
    return row as Person;
  }
  const columns: TableColumn<unknown>[] = [
    { key: 'name', label: 'Name', cell: (row) => personFrom(row).name, sortable: true },
    { key: 'role', label: 'Role', cell: (row) => personFrom(row).role },
  ];
  const rowKey = (row: unknown) => personFrom(row).id;
  let rows: Person[];
  $: rows = people.filter((person) => person.name.toLowerCase().includes(query.toLowerCase()));

  function onChange(event: CustomEvent<{ value: string }>): void {
    query = event.detail.value;
  }
</script>

<main class="lr-native lr-stack lr-gap-l">
  <header class="lr-stack lr-gap-xs">
    <h1>People</h1>
    <p>Svelte binds arrays to known custom-element properties without stringifying them.</p>
  </header>

  <div class="lr-cluster lr-gap-s">
    <lr-input
      bind:this={input}
      label="Filter by name"
      value={query}
      with-clear
      onlr-change={onChange}
    ></lr-input>
    <button type="button" onclick={() => input.select()}>Select filter text</button>
  </div>

  <lr-table
    aria-label="People matching the filter"
    {rowKey}
    {columns}
    {rows}
  ></lr-table>
</main>
